web:
    upload-path: D:/dev/JavaProjects/avatar/
# DataSource Config
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/volunteerhub?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: root
    mvc:
        servlet:
            multipart:
                max-file-size: 10MB
                max-request-size: 10MB
    web:
        resources:
            static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/, file:${web.upload-path}

mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml
volunteerhub:
    jwt:
        secret: f4e2e52034348f86b67cde581c0f9eb5
        expire: 604800
        header: Authorization
