web:
    avatar-path: D:/dev/JavaProjects/avatar/
    video-path: D:/dev/JavaProjects/video/
    videocover-path: D:/dev/JavaProjects/videocover/
# DataSource Config
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/volunteerhub?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: root
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    web:
        resources:
            # 注意这里的配置，如果不配置，可能会导致静态资源无法访问，资源访问的链接的相对路径不能包括下面路径头
            static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/, file:${web.avatar-path}, file:${web.video-path}, file:${web.videocover-path}

server:
    servlet:
        connection-payload-size: -1

mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml
volunteerhub:
    jwt:
        secret: f4e2e52034348f86b67cde581c0f9eb5
        expire: 604800
        header: Authorization
